# Generated by Django 4.1.5 on 2023-02-07 03:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calendar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('title', models.CharField(max_length=191)),
                ('start_dt', models.DateTimeField(db_index=True, verbose_name='Start Datetime')),
                ('end_dt', models.DateTimeField(db_index=True, verbose_name='End Datetime')),
                ('description', models.TextField(blank=True, null=True)),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calendar.calendar')),
            ],
            options={
                'ordering': ['start_dt'],
            },
        ),
    ]
