# Generated by Django 4.1.5 on 2023-03-04 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['start_date', 'start_datetime']},
        ),
        migrations.RemoveField(
            model_name='event',
            name='start_dt',
        ),
        migrations.RemoveField(
            model_name='event',
            name='end_dt',
        ),
        migrations.AddField(
            model_name='event',
            name='start_date',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Start Date'),
        ),
        migrations.AddField(
            model_name='event',
            name='start_datetime',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Start Datetime'),
        ),
        migrations.AddField(
            model_name='event',
            name='end_date',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='End Date'),
        ),
        migrations.AddField(
            model_name='event',
            name='end_datetime',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='End Datetime'),
        ),
        migrations.AddField(
            model_name='event',
            name='is_all_day',
            field=models.BooleanField(default=True),
        ),
    ]
